config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :orders, :except => [:new, :destroy] do
    resources :order_items, :only => [:destroy]
  end
  get 'get_shipping_price/:id' => 'shippings#get_shipping_price'
    
  resources :credit_cards
  resources :countries
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :books do
    resources :ratings
  end
  
  resources :authors
  resources :categories
  post 'set_coupon/:coupon' => 'orders#set_coupon'
  post 'cart/:id'   => 'orders#add_to_cart', as: 'add_to_cart'
  get 'cart'        => 'orders#show_cart'
  get 'cart_clear'  => 'orders#clear_cart', as: 'clear_cart'
  get 'checkout'    => 'orders#checkout'
  post 'place_order' => 'orders#place'
  root 'books#bestsellers'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :user
  has_many :orders

  validates :number, presence: true
  validates :cvv, presence: true
  validates :exp_month, presence: true
  validates :exp_year, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true

  def default!
    current_default_credit_cards = user.credit_cards.where(default: ActiveRecord::Type::Boolean.new.type_cast_from_user(true))
    current_default_credit_cards.each do |card|
      addr.default = ActiveRecord::Type::Boolean.new.type_cast_from_user(false)
      addr.save
    end
    self.default = ActiveRecord::Type::Boolean.new.type_cast_from_user(true)
    self.save
  end

  def is_card_valid?
    # number.gsub(/\s+/, "").size == 16 & cvv.gsub(/\s+/, "").size == 3 to set in validators
     exp_year > Date.today.year or ( exp_year == Date.today.year & exp_month >= Date.today.month )
    
  end

  def to_s
    "%s %s%s %s (%02d/%02d)" % [number[1..4], number[5..6], "** ****", number[-4..-1], exp_month, exp_year]
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  load_and_authorize_resource
  # before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    # @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :cvv, :exp_month, :exp_year, :firstname, :lastname, :user_id)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :cvv %><br>
    <%= f.text_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :exp_month %><br>
    <%= f.number_field :exp_month %>
  </div>
  <div class="field">
    <%= f.label :exp_year %><br>
    <%= f.number_field :exp_year %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<h1>Listing Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Cvv</th>
      <th>Exp month</th>
      <th>Exp year</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= credit_card.number %></td>
        <td><%= credit_card.cvv %></td>
        <td><%= credit_card.exp_month %></td>
        <td><%= credit_card.exp_year %></td>
        <td><%= credit_card.firstname %></td>
        <td><%= credit_card.lastname %></td>
        <td><%= credit_card.user %></td>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @credit_card.number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @credit_card.cvv %>
</p>

<p>
  <strong>Exp month:</strong>
  <%= @credit_card.exp_month %>
</p>

<p>
  <strong>Exp year:</strong>
  <%= @credit_card.exp_year %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @credit_card.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @credit_card.lastname %>
</p>

<p>
  <strong>User:</strong>
  <%= @credit_card.user %>
</p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>