config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :orders, :except => [:new, :destroy] do
    resources :order_items, :only => [:destroy]
  end
  get 'get_shipping_price/:id' => 'shippings#get_shipping_price'
    
  resources :credit_cards
  resources :countries
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :books do
    resources :ratings
  end
  
  resources :authors
  resources :categories
  post 'set_coupon/:coupon' => 'orders#set_coupon'
  post 'cart/:id'   => 'orders#add_to_cart', as: 'add_to_cart'
  get 'cart'        => 'orders#show_cart'
  get 'cart_clear'  => 'orders#clear_cart', as: 'clear_cart'
  get 'checkout'    => 'orders#checkout'
  post 'place_order' => 'orders#place'
  root 'books#bestsellers'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :rating, numericality:{
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10
  }

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  load_and_authorize_resource :book
  load_and_authorize_resource :rating, :through => :book
  # before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    # @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    # byebug
    @rating = Rating.new(rating_params)
    @rating.user = current_user
    @rating.book_id = params[:book_id]

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating.book, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating.book, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to @rating.book, notice: 'Rating was successfully destroyed.' } #было ratings_url
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:review, :rating, :user_id, :book_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for([:book, @rating]) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, class: 'rating' %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Review</th>
      <th>Rating</th>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.review %></td>
        <td><%= rating.rating %></td>
        <td><%= rating.user %></td>
        <td><%= rating.book %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/ratings/show.html.erb
<p>
  <strong>Review:</strong>
  <%= @rating.review %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @rating.book %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>