config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :orders, :except => [:new, :destroy] do
    resources :order_items, :only => [:destroy]
  end
  get 'get_shipping_price/:id' => 'shippings#get_shipping_price'
    
  resources :credit_cards
  resources :countries
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :books do
    resources :ratings
  end
  
  resources :authors
  resources :categories
  post 'set_coupon/:coupon' => 'orders#set_coupon'
  post 'cart/:id'   => 'orders#add_to_cart', as: 'add_to_cart'
  get 'cart'        => 'orders#show_cart'
  get 'cart_clear'  => 'orders#clear_cart', as: 'clear_cart'
  get 'checkout'    => 'orders#checkout'
  post 'place_order' => 'orders#place'
  root 'books#bestsellers'

end

app/models/order.rb
require 'aasm'
class Order < ActiveRecord::Base
  include AASM
  
  # STATUSES = ['canceled','in progress','in queue','in delivery','delivered']
  
  belongs_to :user
  belongs_to :credit_card
  belongs_to :coupon
  has_many :order_items, dependent: :destroy
  has_one :order_shipping
  has_one :shipping, through: :order_shipping
  # belongs_to :billing_address, class_name: 'Address'
  # belongs_to :shipping_address, class_name: 'Address'

  validates :total_price, presence: true
  # validates :completed_date, presence: true
  validates :state, presence: true
  validates :billing_address, presence: true, if: "!self.in_progress?"
  validates :shipping_address, presence: true, if: "!self.in_progress?"


  aasm :column => :state do
    state :in_progress, :initial => true
    state :in_queue
    state :in_delivery
    state :delivered
    state :canceled

    event :process do
      transitions :from => :in_progress, :to => :in_queue
    end
    
    event :deliver do
      transitions :from => :in_queue, :to => :in_delivery
    end
    
    event :done, :success => :record_date do
      transitions :from => :in_delivery, :to => :delivered
    end

    event :cancel, :success => :record_date do
      transitions :from => [:in_progress, :in_queue, :in_delivery], :to => :canceled
    end
  end
  
  def state_enum 
    aasm.states(:permitted => true).map(&:name)
  end

  def record_date
    self.completed_date = DateTime.now
  end
    

  # def cancel!
  #   # byebug
  #   return unless can_modify?
  #   self.state = STATUSES[0]
  #   self.completed_date = DateTime.now
  # end
  
  # def next_state!
  #   return unless can_modify?
  #   current_state_index = STATUSES.index(state)
  #   self.state = STATUSES[current_state_index+1]
  #   self.completed_date = DateTime.now if self.state == STATUSES.last
  # end
  
  def can_modify?
    # completed_date.blank? && state != STATUSES.first && state != STATUSES.last
    in_progress?
  end
  
  def add_item(book, quantity=1)
    # byebug
    book = Book.find(book) unless book.is_a? Book
    return unless can_modify?
    
    item = order_items.where(book: book)
    if item.blank?
      item = self.order_items.new
      item.book = book
      item.price = book.price
      item.quantity = quantity
    else
      item = item.first
      item.quantity += quantity
    end
    item.save
  end
  
  def calculate_total
    # byebug
    return unless can_modify?
    self.total_price = order_items.sum('quantity * price')
    self.total_price *= (1 - coupon.discount / 100) if coupon
  end
  
  def set_shipping(shipping_id=1)
    return unless can_modify?
    shipping = Shipping.find(shipping_id)
    self.order_shipping = OrderShipping.new(shipping: shipping, price: shipping.price)
    
    rescue ActiveRecord::RecordNotFound
    
  end
  
  def set_coupon_by_code(coupon_code)
    return unless can_modify?
    coupon_hash = Coupon.get_coupon_by_code(coupon_code)
    res = coupon_hash[:status]
    if (res == :cleared && !self.coupon)||(res == :ok && self.coupon == coupon_hash[:coupon])
      res = :no_changes
    elsif res == :ok || res == :cleared
      self.coupon = coupon_hash[:coupon]
      calculate_total
      save
    end
    res
  end
  
  def total_price_with_shipping
    total = self.total_price
    total += shipping.price if shipping
    total
  end
  
  def empty!
    order_items.destroy_all
  end
  
  def empty?
    order_items.count == 0
  end
  
  def to_s
    "##{id}"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_resource only: [:index, :show, :edit, :update, :destroy]
  authorize_resource
  # skip_load_resource only: [] 
  # before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    # if Customer 
      # @orders = current_user.recent_orders
    # elsif Manager || Admin 
      # @orders = Order.all
    # end
    # @orders = current_user.orders_by_status
    
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_items = @order.order_items
  end

  # # GET /orders/new
  # def new
  #   @order = Order.new
  # end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    # byebug
    @order.set_shipping(params[:shipping][:id]) if params[:shipping]
    # @order.set_coupon_by_code(params[:coupon]) if params[:coupon]
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /orders/1
  # # DELETE /orders/1.json
  # def destroy
  #   @order.destroy
  #   respond_to do |format|
  #     format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  
  def show_cart
    @order = get_or_create_order_from_session
    @order_items = @order.order_items
    render "cart"
  end
  
  def add_to_cart
    # byebug
    id = params[:id]
    quantity = params[:quantity].to_i
    cart = get_or_create_order_from_session
    cart.add_item(id, quantity)
    cart.save
    redirect_to cart_url
  end
  
  def clear_cart
    begin
      cart = Order.find(session[:order_id])
      cart.destroy
      # cart.cancel!
    ensure
      session[:order_id] = nil
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Cart is now empty.' }
        format.json { head :no_content }
      end
    end
  end
  
  def checkout
    @steps = ['address', 'delivery', 'payment', 'confirm', 'complete']
    @user = current_user
    @order = get_or_create_order_from_session
    render 'orders/checkout/checkout'
  end
  
  def place
    if @order.may_process?
      @order.process
    else
      respond_to do |format|
        format.html { redirect_to @order, notice: "Order can't be processed. Contact with support." }
      end
    end
    redirect_to orders_path
  end
  
  def set_coupon
    @order = get_or_create_order_from_session
    # byebug
    coupon = params[:coupon]
    # return if !coupon
    status = @order.set_coupon_by_code(coupon)
    render json: { total_price: @order.total_price, status: status, coupon: ({code: coupon, discount: @order.coupon.discount} if @order.coupon) }
    # render json: { total_price: 100.00, status: :not_found }
  end
      
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
    
    def get_or_create_order_from_session
      begin
        order = Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        params = {shipping_address: '_', billing_address: '_'}
        params.merge({ user: current_user }) if user_signed_in?
        order = Order.create(params)
        session[:order_id] = order.id
      end
      order
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:state, :completed_date, :total_price, :user_id, :credit_card_id, :shipping_address, :billing_address)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :completed_date %><br>
    <%= f.datetime_select :completed_date %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :credit_card_id %><br>
    <%= f.text_field :credit_card_id %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_area :shipping_address %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_area :billing_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/cart.html.erb
<!--<p>-->
<!--  <strong>Credit card:</strong>-->
<!--  <%= @order.credit_card %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Shipping address:</strong>-->
<!--  <%= @order.shipping_address %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Billing address:</strong>-->
<!--  <%= @order.billing_address %>-->
<!--</p>-->

<table>
  <thead>
    <tr>
      <th></th>
      <th>Book</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each_with_index do |order_item, index| %>
      <tr id=<%="order_item_#{order_item.id}"%>>
        <td class='book_image'>
          <%= link_to book_path(order_item.book) do%>
            <%= image_tag order_item.book.image.url(:thumb) %>
          <% end %>
          </td>
        <td class='book_descr'>
          <h4>
            <%= link_to book_path(order_item.book) do%>
              <%= order_item.book %>
            <% end %>
          </h4>
          <%= order_item.book.description %>
        </td>
        <td class='book_price'><%= order_item.price %></td>
        <td class='book_quantity'><%= order_item.quantity %></td>
        <!--<td><%= number_field_tag order_item.quantity, 1, min: 1, max: 99, id: 'book-quantity' %></td>-->
        <td class='book_sum'><%= order_item.price * order_item.quantity %></td>
        <td><%= link_to 'X', order_order_item_path(order_item.order, order_item, cart: true), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3"></td>
      <td><strong>Subtotal:&nbsp</strong></td>
      <td>
        <strong id=item_total>
          <%= @order.total_price %>
        </strong>
      </td>
    </tr>      
  </tbody>
</table>
<br/>
<%= link_to 'Empty cart', clear_cart_path, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to 'Continue shopping', books_path, class: 'btn btn-primary' %>
<div  class="pull-right">
	<p class="notice"></p>
  <%= label_tag @order.coupon, @order.coupon ? @order.coupon.code + '(' + @order.coupon.discount.to_s + '%)' : '', id: 'label_coupon_code', style: @order.coupon ? '': 'display: none;'%>
  <%= text_field_tag @order.coupon, @order.coupon ? @order.coupon.code : nil, placeholder: 'Coupon code', id: 'edit_coupon_code', style: @order.coupon ? 'display: none;' : '' %>
  <%= button_tag t(:apply), type: 'button', class: 'btn btn-info', id: 'apply_coupon_btn', remote: true, style: @order.coupon ? 'display: none;' : ''  %>
  <%= link_to 'Checkout', checkout_path, class: 'btn btn-success' %>
</div>

<script>
  function toggleCouponView(){
    $('#edit_coupon_code').toggle();
    $('#apply_coupon_btn').toggle();
    $('#label_coupon_code').toggle();
  };
  $('#label_coupon_code').click(function (){
    toggleCouponView();
  });
  $('#apply_coupon_btn').click(function (){
    $.ajax({
      type: "POST",
      url: 'set_coupon/' + ($('#edit_coupon_code')[0].value != '' ? $('#edit_coupon_code')[0].value : '~=EMPTY=~'),
      dataType: "json"     
    })
    .then(function( json ) {
      if (json.status == 'ok') {
        $('.notice').html('Success');
        setTimeout('$(".notice").html("")', 3000);
        $('#item_total')[0].textContent = json.total_price;
        // $('#edit_coupon_code').hide();
        // $('#apply_btn').hide();
        $('#label_coupon_code')[0].textContent = json.coupon.code + "(" + json.coupon.discount +"%)"
        toggleCouponView();
      } else if (json.status == 'expired') {
        $(".notice").html('Coupon was expired');
        setTimeout('$(".notice").html("")', 3000);
        // $('#label_coupon_code')[0].textContent = ''
      } else if (json.status == 'not_found') {
        $(".notice").html('Coupon is not found');
        setTimeout('$(".notice").html("")', 3000);
        // $('#label_coupon_code')[0].textContent = ''
      } else if (json.status == 'cleared') {
        $(".notice").html('Coupon cleared');
        setTimeout('$(".notice").html("")', 3000);
        $('#label_coupon_code')[0].textContent = ''
        $('#item_total')[0].textContent = json.total_price;
      } else if (json.status == 'no_changes') {
        $(".notice").html('No changes');
        setTimeout('$(".notice").html("")', 3000);
        if ($('#label_coupon_code')[0].textContent != '') {
          toggleCouponView();
        }
      };
    })
   });
</script>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Completed date</th>
      <th>Total price</th>
      <th>User</th>
      <th>Credit card</th>
      <th>Shipping address</th>
      <th>Billing address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.state %></td>
        <td><%= order.completed_date %></td>
        <td><%= order.total_price %></td>
        <td><%= order.user %></td>
        <td><%= order.credit_card %></td>
        <td><%= order.shipping_address %></td>
        <td><%= order.billing_address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Completed date:</strong>
  <%= @order.completed_date %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
  <strong>Credit card:</strong>
  <%= @order.credit_card %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @order.billing_address %>
</p>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Image</th>
      <th>Book</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each_with_index do |order_item, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td>
          <%= link_to book_path(order_item.book) do%>
            <%= image_tag order_item.book.image.url(:thumb) %>
          <% end %>
          </td>
        <td>
        <td>
          <%= link_to book_path(order_item.book) do%>
            <%= order_item.book %>
          <% end %>
        </td>
        <td><%= order_item.price %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.price * order_item.quantity %></td>
        <td><%= link_to 'Destroy', order_order_item_path(order_item.order, order_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3"></td>
      <td><strong>Total:</strong></td>
      <td>
        <strong>
          <%= @order.total_price %>
        </strong>
      </td>
    </tr>

  </tbody>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>