config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :orders, :except => [:new, :destroy] do
    resources :order_items, :only => [:destroy]
  end
  get 'get_shipping_price/:id' => 'shippings#get_shipping_price'
    
  resources :credit_cards
  resources :countries
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :books do
    resources :ratings
  end
  
  resources :authors
  resources :categories
  post 'set_coupon/:coupon' => 'orders#set_coupon'
  post 'cart/:id'   => 'orders#add_to_cart', as: 'add_to_cart'
  get 'cart'        => 'orders#show_cart'
  get 'cart_clear'  => 'orders#clear_cart', as: 'clear_cart'
  get 'checkout'    => 'orders#checkout'
  post 'place_order' => 'orders#place'
  root 'books#bestsellers'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  has_many :ratings

  validates :title, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  
  has_attached_file :image, styles: { large: "600x600>", thumb: "200x200>" }, default_url: "blank_book.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  
  scope :bestsellers, lambda {|count=nil|
    OrderItem.joins(:book)
    .group(:book)
    .order('sum_quantity desc')
    .limit(count)
    .sum(:quantity).keys
  }
  
  scope :by_category, lambda {|category|
    where(category: category)
  }

  def to_s
    "#{title} by #{author}"
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource  
  # before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = @books.by_category(params[:category]) if params[:category]
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @ratings = @book.ratings.limit(5)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def bestsellers
    @bestsellers = Book.bestsellers(3)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :price, :stock, :author_id, :category_id, :image)
    end
end

app/helpers/books_helper.rb
module BooksHelper
  def carousel_for(book_items)
    Carousel.new(self, book_items).html
  end

  class Carousel
    def initialize(view, book_items)
      @view = view
      @book_items = book_items
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :book_items, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = book_items.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = book_items.map.with_index { |book_item, index| slide_tag(book_item, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(book_item, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, options) do
        render(partial: 'card', object: book_item)
      end
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/views/books/_card.html.erb
<div class="row">
  <div id="book-header" class="col-lg-12">
    <div id="book-title">
        <%= card.title %>
    </div>
    <div id="book-author">
        <em>
          by 
          <%= link_to card.author, card.author %>
        </em>
    </div>
  </div>
</div>

<div class="row">
  <div id="book-details">    
    <div id="book-image" class="col-xl-2 col-lg-3 col-md-4 col-sm-5 box">
      <%= image_tag card.image.url(:thumb), class: 'content' %>
    </div>
    
    <div id="book-decription" class="col-xl-10 col-lg-9 col-md-8 col-sm-7">
      <%= card.description %>
      <br/>
      <br/>
      <div id="fb-root"></div>
      <div
        class="fb-like"
        data-href= <%= book_url(card) %>
        data-share="true"
        data-width="450"
        data-show-faces="true">
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div id="book-buyer-section" class="col-lg-3 col-lg-offset-3 col-md-4 col-md-offset-4 col-sm-5 col-sm-offset-4">
  <%= form_tag add_to_cart_path(card), method: 'POST' do %>
    <div  id="to-order" class="input-group">
      <span class="input-group-addon">
        <strong>$<%= card.price %></strong>
      </span>
      <%= number_field_tag 'quantity', 1, min: 1, max: 99, class: 'form-control', id: 'book-quantity' %>
      <span class="input-group-btn">
        <%= submit_tag "Add to cart", class: 'btn btn-success' %>
      </span>
    </div>
  <% end %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= image_tag @book.image.url(:thumb) if @book.image.exists?(:thumb) %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/bestsellers.html.erb
<div id = "bestsellerCarousel" class = "carousel slide">
   
   <!-- Carousel indicators -->
   <ol class = "carousel-indicators">
      <% @bestsellers.count.times do |i| %>
           <li data-target = "#bestsellerCarousel" data-slide-to = "<%= i %>" class = <%= i==0 ? "active" : "" %>></li>
       <% end%>
   </ol>   
   
   <!-- Carousel items -->
   <div class = "carousel-inner">
      <% @bestsellers.each_with_index do |item, index| %>
          <div class = "item<%= index == 0 ? " active" : "" %>">
            <div id="background">
            <%= render partial: 'card', object: item %>
            </div>
          </div>
      <% end %>
   </div>
   
   <!-- Carousel nav -->
   <a class = "carousel-control left" href = "#bestsellerCarousel" data-slide = "prev">&lsaquo;</a>
   <a class = "carousel-control right" href = "#bestsellerCarousel" data-slide = "next">&rsaquo;</a>
   
</div>

<center>
   <h2>Welcome to our amazing bookstore!<br/>Choose anything you wish, we'll ship it anywhere!</h2>
</center>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Shop</h1>


<div class="col-xs-10">
  <div class="row">
    <% @books.each_with_index do |book, index| %>
    
        <div class="col-xs-4 col-min portfolio-item">
            <div class="box">
              <%= link_to book_path(book) do %>
                  <%= image_tag( book.image.url(:thumb), class: 'img-responsive content', alt: 'book.title') %>
              <% end %>
            </div>
            <h3>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </h3>
            <p>
              <strong>$<%= book.price %></strong>
              <!--<%= link_to 'Add to cart', add_to_cart_path(book) %>-->
            </p>
        </div>
    <% end %>
  </div>
</div>
<div class="col-xs-2">
  <div class="shop">
    <h5 class="text-muted">SHOP BY CATEGORIES</h5>
    <div class="row">
        <%- Category.all.each do |category| %>
          <div class="category">
            <%= link_to category.title, books_path(category: category) %>
          </div>
        <% end %>
        <%= link_to 'All', books_path %>
    </div>
  </div>
</div>

<br>
<%- if false %>
  <%= link_to 'New Book', new_book_path %>
<%- end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<%= render partial: 'card', object: @book %>

<h2>Reviews</h2>
<%= link_to 'Add review to this book', new_book_rating_path(book_id: @book.id) %>
<% @ratings.each do |item| %>
    <p>
        <%= item.rating %>
    </p>
    <p>
        by <%= item.user %>
    </p>
    <p>
        <%= item.created_at %>
    </p>
    <p>
        <%= item.review %>
    </p>
<% end %>

<% if false %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', :back %>
<% end %>